# Basic dependabot.yml to update gomod & GitHub Actions
version: 2
updates:
  # Maintain dependencies for the core library
  - package-ecosystem: "gomod"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    reviewers:
      - "shruggr"
      - "rohenaz"
    assignees:
      - "shruggr"
      - "rohenaz"
    labels:
      - "chore"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "shruggr"
      - "rohenaz"
    assignees:
      - "shruggr"
      - "rohenaz"
    labels:
      - "chore"
    open-pull-requests-limit: 10
